### PR TITLE
Support python 3.9 and minio 7.2.7

### PR DESCRIPTION
**Pull request by novama**
https://github.com/IamTugy/pyminio/issues/21
- [ ] All tests are green.

### CODE REVIEW

**Review by IamTugy — APPROVED** [review]

**Comment by IamTugy** [comment]
Nice!

**Comment by IamTugy** [comment]
@novama Hey, this actually wont make this repo to support python 3.9, im working on a solution atm :)

**Comment by IamTugy** [comment]
Hey @novama, Ive added support for python 3.9+.
Feel free to contribute if you want in the future and dont forget to sync-up with the latest updates :) 
the latest version is 0.3.1

If you want to contribute in the future, check that the tests are passing and add more if needed

**Comment by novama** [comment]
Thanks @IamTugy!

**Pull request merged**
